layout_spectrum: 0
color:
  saturation: 1
  brandStrength: 0.9570665
  lightness: 1
  rhythmicContrast: 1
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.2089151
name: Jeremy Brown
